### ISSUE TITLE
Adding get_controls function

### ISSUE THREAD

**Issue by sunnyszy** [CohenLabPrinceton/Ventilator-Dev#10]
Besides the `set_controls()` interface, we have in coordinator and controller, I feel we should also define `get_controls()` interface. This allows:

- Easier unit test for `set_controls()`
- After set, the coordinator/controller can immediately call get to verify the set results. This gives a consistency guarantee. 

My current definition: 
```
def get_controls(self, control_setting_name: ControlSettingName) -> ControlSettings:
```

**Comment by sunnyszy** [comment]
If you guys feel okay, @mschottdorf can you add the function to the controller?

**Comment by gdoubleyew** [comment]
Sounds good to me

**Comment by mschottdorf** [comment]
yep, sure!

**Comment by sunnyszy** [comment]
@mschottdorf FYI I added that yesterday as it is only copying your get_controls implementation :D
