### ISSUE TITLE
Implement internal threading in Controller

### ISSUE THREAD

**Issue by sunnyszy** [CohenLabPrinceton/Ventilator-Dev#15]
Would you like to implement internal threading in ControlModuleSimulator, such that it would update the state after start? I would assume this would just refactor some code from your notebook to the ControlModuleSimulator class. 

To be specific, I would like the Simulator has two functions: start(), stop(). So the GUI can have a button to click start/stop. Once start() is called, the simulator updated its state periodically. And the update stops when the stop is called.

**Comment by mschottdorf** [comment]
Sure, I can do that

**Comment by sunnyszy** [comment]
Thank you, Manuel!

**Comment by mschottdorf** [comment]
done, see pull request
