### ISSUE TITLE
Error handling in vent.io

### ISSUE THREAD

**Issue by CommReteris** [CohenLabPrinceton/Ventilator-Dev#38]
Need to make sure all possible exceptions & hangs are caught.

See: [This](https://github.com/CohenLabPrinceton/Ventilator-Dev/pull/31#discussion_r418366771) and 
[this.](https://github.com/CohenLabPrinceton/Ventilator-Dev/pull/31#discussion_r418367429)

**Comment by sneakers-the-rat** [comment]
proposed a generalized method of doing this here:
https://github.com/CohenLabPrinceton/Ventilator-Dev/issues/35

give it a shot, haven't had a minute to actually test it, just a draft. All it requires is for us to build some logging system. The logging module is solid and I can draft up a way of spawning logging objects for each of the separate modules.

**Comment by sneakers-the-rat** [comment]
scuse me - that general pattern of having a decorator to wrap sensitive calls in a try/except/finally block, sensor readings would probs look a bit different since they don't need locking.
