### ISSUE TITLE
Duplication of function in values

### ISSUE THREAD

**Issue by sneakers-the-rat** [CohenLabPrinceton/Ventilator-Dev#47]
At some point an additional variable `values.controllable_values` was created that has the same function as `values.CONTROL` . (same thing with `non_controllable_values` and `SENSOR`) In this commit there are already places where they are inconsistent, so i hope no illustration is needed as to why that’s less than optimal:

https://github.com/CohenLabPrinceton/Ventilator-Dev/blob/e05cb8095d44988918725dca138451ecce6bc7e1/vent/common/values.py#L23

https://github.com/CohenLabPrinceton/Ventilator-Dev/blob/e05cb8095d44988918725dca138451ecce6bc7e1/vent/common/values.py#L187

This can be fixed in one of two ways, in my opinion:

- use `values.CONTROL.keys()` in place of `values.controllable_values`, or
- have a single `VALUES = odict()` dictionary that has _all_ the parameterizations that are currently in `CONTROL` and `SENSOR`, and then do something like `[value for value in VALUES if value in values.controllable_values]` to get the actual values themselves.

I'm partial to the first option because it's parsimonious and gives stable objects instead of constantly needing to iterate over a list, but either one is fine with me -- having both as is currently the case is not fine with me as it already is causing bugs lol.

**Comment by mschottdorf** [comment]
I also prefer option 1, as this is close to how most of the code is structured.
