### ISSUE TITLE
Coupling the pressure sensor to the respiratory circuit

### ISSUE THREAD

**Issue by CohenLabPrinceton** [CohenLabPrinceton/Ventilator-Dev#83]
We need to sterilely couple the pressure sensor to a sampling port *in the airway* (e.g. at the wye or immediately upstream). This could be a combined HMEF or coupling tube. 

- [x] Sofie was going to handle the HMEF check.

- [x] Tom/Julie/Daniel were looking at general coupling tubes.

**Comment by zajdel** [comment]
Right now, this is being done via the D-lite, but this isn't going to be the long-term solution.

**Comment by zajdel** [comment]
HMEF is working well, and has been tested with the control loop.
