### ISSUE TITLE
TestReport: UI and Units of Measure

### ISSUE THREAD

**Issue by ProfDJCohen** [CohenLabPrinceton/Ventilator-Dev#88]
Ref 1: CR501 201.7.4.3 / 80601-2-80

Units of measure

a) All gas volume, flowrate and leakage specifications:

- [x] 1) shall be expressed at STPD (STANDARD TEMPERATURE AND PRESSURE, DRY);

- [x] 2) except those associated with the VBS which shall be expressed at BTPS (BODY

TEMPERATURE AND PRESSURE, SATURATED).

- [x] bb) The unit of AIRWAY PRESSURE measurement shall be capable of being configured to be expressed in hPa

**Comment by ProfDJCohen** [comment]
@sneakers-the-rat we need a 'units' setting where we can switch to hPa. I am not sure about the reporting of BTPS since we're not measuring anything that would be affected by that (I think).

**Comment by sneakers-the-rat** [comment]
changing value over 2 orders of magnitude is actually sorta tricky when ur space constrained. got most of the way there but need to quit for the night.

**Comment by sneakers-the-rat** [comment]
https://github.com/CohenLabPrinceton/Ventilator-Dev/commit/4c7c929df47941c2f3d7aad93c31c2311e44b339

**Comment by sneakers-the-rat** [comment]
surprisingly hard to do
